config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :wiki_entries do
    resources :comments, controller:"wiki_comments", shallow:true
    resources :wiki_comments, shallow:true
  end
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/controllers/sei_processes_controller.rb
class SeiProcessesController < ApplicationController
  before_action :set_sei_process, only: [:show, :edit, :update, :destroy]

  ##
  # Ação index da classe SeiProcess.
  # Renderiza a view index, que exibe os processos e solicitações criados (dependente do usuário que está logado).
  # GET /sei_processes
  def index
    # Filtra solicitações baseadas nos estados marcados como visíveis
    @all_statuses = SeiProcess.all_statuses
    session[:statuses] = params[:statuses] || session[:statuses] || @all_statuses.zip([]).to_h
    @status_filter = session[:statuses].keys
    
    # Lista todas as solicitações de credenciamento para um administrador
    if current_user.role == "administrator"
      @sei_processes = SeiProcess.where(status: @status_filter)
    # Lista as solicitações próprias para um professor
    else
      @my_processes = SeiProcess.where(user_id: current_user.id, status: @status_filter)
    end
  end

  ##
  # Ação show da classe SeiProcess. Mostra detalhes de um registro criado.
  # GET /sei_processes/1
  def show
  end

  ##
  # Ação new da classe SeiProcess. Renderiza página para criação de um registro.
  # Recebe também o registro Requisitos de Credenciamento para exibição na view new.
  # GET /sei_processes/new
  def new
    # Renderiza Requisitos de Credenciamento, caso existam, na página de criação de processo ou de abrir solicitação de credenciamento
    @requirements = Requirement.find_by(title: 'Requisitos de Credenciamento')
    @sei_process = SeiProcess.new
  end

  ##
  # Ação edit da classe SeiProcess. Renderiza página para atualizar um registro.
  # GET /sei_processes/1/edit
  def edit
  end

  ##
  # Método responsável por criar um registro com os dados inseridos na view new.
  # Recebe os dados da view new e faz o tratamento para decidir se o registro é válido ou não.
  # Redireciona para a view index caso os dados sejam válidos.
  # POST /sei_processes
  def create
    # Faz correções de entradas inválidas baseando-se nos dados do usuário logado
    mandatory_params = {'user_id' => current_user.id, 'status' => 'Espera', 'code' => '0'}
    @sei_process = SeiProcess.new(sei_process_params.merge(mandatory_params))

    respond_to do |format|
      # Quando condições da model forem cumpridas, cria um novo registro no banco, redireciona para pagina index da tabela atual e mostra uma mensagem de sucesso 
      if @sei_process.save
        format.html { redirect_to sei_processes_url, notice: 'Processo aberto com sucesso!' }
      # Mostra uma mensagem de erro se condições da model não forem cumpridas
      else
        format.html { render :new }
      end
    end
  end

  ##
  # Método responsável por atualizar um registro com os dados inseridos na view edit.
  # Recebe os dados da view edit e faz o tratamento dos dados modificados pelo usuário.
  # Caso os dados sejam válidos, o registro é atualizado no banco e um novo registro de Accreditation correspondente é criado e o usuário é redirecionado para a view index.
  # PATCH/PUT /sei_processes/1
  def update
    respond_to do |format|
      # Quando condições da model forem cumpridas, atualiza o registro no banco, redireciona para pagina index da tabela atual e mostra uma mensagem de sucesso 
      if @sei_process.update(sei_process_params)
        format.html { redirect_to sei_processes_url, notice: 'Processo atualizado com sucesso!' }

        # Cria o credenciamento correspondente aa solicitação aprovada
        if @sei_process.status == 'Aprovado' && (Accreditation.find_by(sei_process: @sei_process.id) == nil)
          Accreditation.create!(user_id: @sei_process.user_id, sei_process_id: @sei_process.id)
        end

      # Mostra uma mensagem de erro se condições da model não forem cumpridas
      else
        format.html { render :edit }
      end
    end
  end

  ##
  # Método responsável por excluir um registro salvo na tabela.
  # Redireciona para a view index.
  # DELETE /sei_processes/1
  def destroy
    respond_to do |format|
      # Mensagem de sucesso ao excluir processo ou solicitação quando condições da model forem cumpridas
      if @sei_process.destroy
        format.html { redirect_to sei_processes_url, notice: 'Processo excluído com sucesso!' }
      # Mensagem de erro se condições da model não forem cumpridas
      else
        format.html { redirect_to sei_processes_url, notice: 'Erro: não foi possível excluir o processo!' }
      end
    end
  end

  private
    # Define parametros de Processo
    def set_sei_process
      @sei_process = SeiProcess.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sei_process_params
      params.require(:sei_process).permit(:user_id, :status, :code, documents: [])
    end
end

app/helpers/sei_processes_helper.rb
module SeiProcessesHelper
end

app/views/sei_processes/_form.html.erb
<%= form_with(model: sei_process, local: true) do |form| %>
  <% if sei_process.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sei_process.errors.count, "error") %> prohibited this sei_process from being saved:</h2>

      <ul>
      <% sei_process.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sei_processes/_form_edit.html.erb
<%= form_with(model: sei_process, local: true) do |form| %>
  <% if sei_process.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sei_process.errors.count, "erro") %> impediu este processo de ser salvo:</h2>

      <ul>
      <% sei_process.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status, "Avaliar" %>
    <%= form.radio_button :status, 'Aprovado', id: 'Aprovado', :checked => true %> Aprovado
    <%= form.radio_button :status, 'Rejeitado', id: 'Rejeitado' %> Rejeitado
  </div>

  <div class="actions">
    <%= form.submit "Enviar" %>
  </div>
<% end %>

app/views/sei_processes/_form_new.html.erb
<%= form_with(model: sei_process, local: true) do |form| %>
  <% if sei_process.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sei_process.errors.count, "erro") %> impediu este processo de ser salvo:</h2>

      <ul>
      <% sei_process.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id %>
  </div>

  <div class="field">
    <%= form.hidden_field :status %>
  </div>

  <div class="field">
    <%= form.hidden_field :code %>
  </div>

  <div class="field">
    <%= form.label :documents, "Documentos" %>
    <%= form.file_field :documents, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit "Enviar" %>
  </div>
<% end %>

app/views/sei_processes/_index_admin.html.erb
<table>
    <thead>
        <tr>
        <th>Nome</th>
        <th>Matrícula</th>
        <th>Código do Processo</th>
        <th>Status</th>
        <th colspan="1"></th>
        </tr>
    </thead>

    <tbody>
        <% @sei_processes.each do |sei_process| %>
        <tr>
            <td><%= sei_process.user.full_name %></td>
            <td><%= sei_process.user.registration %></td>
            <td><%= sei_process.id %></td>
            <td><%= sei_process.status %></td>
            <% if sei_process.status != 'Espera' %>
            <td><%= link_to 'Mostrar', sei_process_path(sei_process) %></td>
            <% else %>
            <td><%= link_to 'Avaliar', edit_sei_process_path(sei_process) %></td>
            <% end %>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/sei_processes/_index_user.html.erb
<table>
    <thead>
        <tr>
        <th>Código do Processo</th>
        <th>Status</th>
        <th colspan="1"></th>
        </tr>
    </thead>

    <tbody>
        <% @my_processes.each do |sei_process| %>
        <tr>
            <td><%= sei_process.id %></td>
            <td><%= sei_process.status %></td>
            <td><%= link_to 'Mostrar', sei_process_path(sei_process) %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/sei_processes/_show_accreditation_requirements.html.erb
<% if @requirements != nil %>
  <h2><%= @requirements.title %></h2>
  <%= @requirements.content %>

  <% if @requirements.documents.attached? %>
    <p>
      <strong>Documentos Necessários:</strong>
      <% @requirements.documents.each do | document | %>
        <div>
          <%= link_to document.filename, rails_blob_path(document, disposition: 'attachment') %>
        <div>
      <% end %>
    </p>
  <% end %>
<% end %>

app/views/sei_processes/edit.html.erb
<h1><%= "Processo #{@sei_process.id}" %></h1>

<p>
  <strong>Nome:</strong>
  <%= @sei_process.user.full_name %>
</p>
<p>
  <strong>Matrícula:</strong>
  <%= @sei_process.user.registration %>
</p>

<% if @sei_process.documents.attached? %>
  <p>
    <strong>Documentos anexados:</strong>
    <% @sei_process.documents.each do | document | %>
      <div>
        <%= link_to document.filename, rails_blob_path(document, disposition: 'attachment') %>
      <div>
    <% end %>
  </p>
<% end %>

<%= render 'form_edit', sei_process: @sei_process %>

<%= link_to 'Voltar', sei_processes_path %>

app/views/sei_processes/index.html.erb
<p id="notice"></p>

<h1>SEI Processos</h1>

<%= form_tag sei_processes_path, :method => :get, id: 'statuses_form' do %>
    <% @all_statuses.each do |status| %>
      <%= check_box_tag "statuses[#{status}]", 'yes', @status_filter.include?(status), id: "statuses_#{status}" %>
      <%= status %>
    <% end %>
    <%= submit_tag "Atualizar", id: 'statuses_submit' %>
<% end %>
<br/>

<% if current_user.role == "administrator" %>
  <%= render 'index_admin' %>
<% else %>
  <%= render 'index_user' %>
<% end %>

<br/>
<%= link_to 'Abrir Novo Processo', new_sei_process_path %>
<br/>
<%= link_to 'Página Inicial', home_index_path %>

app/views/sei_processes/new.html.erb
<h1>Abrir Processo</h1>

<% if (current_user.role == 'administrator') || (current_user.role == 'professor') %>
  <%= render 'show_accreditation_requirements' %>
<% end %>

<%= render 'form_new', sei_process: @sei_process %>

<% if current_user.role == 'professor' %>
  <br/>Voltar para<br/>
  <%= link_to 'Meus Processos', sei_processes_path %>
  <%= link_to 'Meus Credenciamentos', accreditations_path %>
<% else %>
  <%= link_to 'Voltar', sei_processes_path %>
<% end %>

app/views/sei_processes/show.html.erb
<h1><%= "Processo #{@sei_process.id}" %></h1>

<p>
  <strong>Nome:</strong>
  <%= @sei_process.user.full_name %>
</p>
<p>
  <strong>Matrícula:</strong>
  <%= @sei_process.user.registration %>
</p>

<% if @sei_process.documents.attached? %>
  <p>
    <strong>Documentos anexados:</strong>
    <% @sei_process.documents.each do | document | %>
      <div>
        <%= link_to document.filename, rails_blob_path(document, disposition: 'attachment') %>
      <div>
    <% end %>
  </p>
<% end %>

<p>
  <strong>Status:</strong>
  <%= @sei_process.status %>
</p>

<%= link_to 'Voltar', sei_processes_path %>